tmp:
  path: ~/Devel/Projects/tmp/

yandex-geocoder:
  path: ~/Devel/Projects/main/yandex-geocoder/
  instructions:
    - source ./.env/bin/activate

goto-project-rs:
  path: ~/Devel/Projects/main/goto-project-rs/

book:
  path: ~/Devel/Projects/tdd-guns/book/

book-ui:
  path: ~/Devel/Projects/tdd-guns/book-ui/
