tmp:
  path: ~/Devel/Projects/tmp/

yandex-geocoder:
  path: ~/Devel/Projects/main/yandex-geocoder/
  instructions:
    - source ./.env/bin/activate

goto-project-rs:
  path: ~/Devel/Projects/main/goto-project-rs/

tinkoff-api:
  path: ~/Devel/Projects/main/tinkoff-api/
  instructions:
    - source ./.env/bin/activate

tinkoff-bank-client-rs:
  path: ~/Devel/Projects/main/tinkoff-bank-client-rs/

guidebook:
  path: ~/Devel/Projects/tourist-app/guidebook/
  instructions:
    - source ./.env/bin/activate
