guidebook:
  path: ~/Devel/tourist-app/guidebook/
  instructions:
    - source ./.venv/bin/activate

yandex-geocoder:
  path: ~/Devel/main/yandex-geocoder/
  instructions:
    - source ./.venv/bin/activate

goto-project-rs:
  path: ~/Devel/main/goto-project-rs/

tinkoff-bank-client-rs:
  path: ~/Devel/main/tinkoff-bank-client-rs/

tinkoff-copier:
  path: ~/Devel/main/tinkoff-copier/

pytest-aiohttp-client:
  path: ~/Devel/main/pytest-aiohttp-client/
  instructions:
    - source ./.venv/bin/activate
