backoffice:
  path: ~/Devel/Projects/backoffice/src/
  instructions:
    - source ~/Devel/Envs/py3_backoffice/bin/activate

blog-api:
  path: ~/Devel/Projects/blog-api/
  instructions:
    - source ~/Devel/Envs/py3_blog_api/bin/activate

cryptomaniac512.github.io:
  path: ~/Devel/Projects/cryptomaniac512.github.io/

goto-project:
  path: ~/Devel/Projects/goto-project/
  instructions:
    - source ~/Devel/Envs/py3_goto-project/bin/activate

insta:
  path: ~/Devel/Projects/insta/
  instructions:
    - source ~/Devel/Envs/py3_insta/bin/activate

markdown-full-yaml-metadata:
  path: ~/Devel/Projects/python-markdown-full-yaml-metadata/
  instructions:
    - source ~/Devel/Envs/py3_markdown_full_yaml_metadata/bin/activate

md-loader:
  path: ~/Devel/Projects/python-static-api-generator-md-loader/
  instructions:
    - source ~/Devel/Envs/py3_static_api_generator_md_loader/bin/activate

root-files:
  path: ~/Devel/Projects/root-files/

static-api-generator:
  path: ~/Devel/Projects/python-static-api-generator/
  instructions:
    - source ~/Devel/Envs/py3_static_api_generator/bin/activate

nvim:
  path: ~/.config/nvim/

learn-rust:
  path: ~/Devel/Projects/learn_rust/

yandex-geocoder:
  path: ~/Devel/Projects/yandex-geocoder
  instructions:
    - source ~/Devel/Envs/py3_yandex-geocoder/bin/activate

try-flask-restful:
  path: ~/Devel/Projects/try-flask-restful
  instructions:
    - source ~/Devel/Envs/py3_try-flask-restful/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

dotenv-config:
  path: ~/Devel/Projects/dotenv-config
  instructions:
    - source ~/Devel/Envs/py3_dotenv-config/bin/activate

yafas-server:
  path: ~/Devel/Projects/yafas-server
  instructions:
    - source ~/Devel/Envs/py3_yafas-server/bin/activate

yafas-website:
  path: ~/Devel/Projects/yafas-website

yafas-infrastructure:
  path: ~/Devel/Projects/yafas-infrastructure

build-trigger:
  path: ~/Devel/Projects/build-trigger
  instructions:
    - source ~/Devel/Envs/py3_build-trigger/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

yafas-web:
  path: ~/Devel/Projects/yafas-web
  instructions:
    - PATH="node_modules/.bin:$PATH"

bn2-backend:
  path: ~/Devel/Projects/bn2-backend/src/
  instructions:
    - source ~/Devel/Envs/py3_bn2-backend/bin/activate

bn2-frontend:
  path: ~/Devel/Projects/bn2-frontend/

learn_typescript:
  path: ~/Devel/Projects/learn_typescript
  instructions:
    - PATH="node_modules/.bin:$PATH"

roistat-aggregator:
  path: ~/Devel/Projects/roistat-aggregator
  instructions:
    - source ~/Devel/Envs/py3_roistat-aggregator/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

try-falcon:
  path: ~/Devel/Projects/try-falcon
  instructions:
    - source ~/Devel/Envs/py3_try-falcon/bin/activate

pytest-falcon-client:
  path: ~/Devel/Projects/pytest-falcon-client/
  instructions:
    - source ~/Devel/Envs/py3_pytest-falcon-client/bin/activate

backoffice-client:
  path: ~/Devel/Projects/backoffice-client/
  instructions:
    - source ~/Devel/Envs/py3_backoffice-client/bin/activate

flask-sqlalchemy:
  path: ~/Devel/Projects/flask-sqlalchemy
  instructions:
    - source ~/Devel/Envs/py3_flask-sqlalchemy/bin/activate

learn-elm:
  path: ~/Devel/Projects/learn-elm
  instructions:
    - PATH="node_modules/.bin:$PATH"

try-elm:
  path: ~/Devel/Projects/try-elm
  instructions:
    - PATH="node_modules/.bin:$PATH"
