backoffice:
  path: ~/Devel/Projects/backoffice/src/
  instructions:
    - source ~/Devel/Envs/py3_backoffice/bin/activate

backoffice-client:
  path: ~/Devel/Projects/backoffice-client/
  instructions:
    - source ~/Devel/Envs/py3_backoffice-client/bin/activate

backoffice-frontend:
  path: ~/Devel/Projects/backoffice-frontend
  instructions:
    - PATH="node_modules/.bin:$PATH"

bn2-backend:
  path: ~/Devel/Projects/bn2-backend/src/
  instructions:
    - source ~/Devel/Envs/py3_bn2-backend/bin/activate

bn2-frontend:
  path: ~/Devel/Projects/bn2-frontend/

build-trigger:
  path: ~/Devel/Projects/build-trigger
  instructions:
    - source ~/Devel/Envs/py3_build-trigger/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

dotenv-config:
  path: ~/Devel/Projects/dotenv-config
  instructions:
    - source ~/Devel/Envs/py3_dotenv-config/bin/activate

goto-project:
  path: ~/Devel/Projects/goto-project/
  instructions:
    - source ~/Devel/Envs/py3_goto-project/bin/activate

insta:
  path: ~/Devel/Projects/insta/
  instructions:
    - source ~/Devel/Envs/py3_insta/bin/activate

nvim:
  path: ~/.config/nvim/

pytest-falcon-client:
  path: ~/Devel/Projects/pytest-falcon-client/
  instructions:
    - source ~/Devel/Envs/py3_pytest-falcon-client/bin/activate

roistat-aggregator:
  path: ~/Devel/Projects/roistat-aggregator
  instructions:
    - source ~/Devel/Envs/py3_roistat-aggregator/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

root-files:
  path: ~/Devel/Projects/root-files/

yafas-infrastructure:
  path: ~/Devel/Projects/yafas-infrastructure

yafas-server:
  path: ~/Devel/Projects/yafas-server
  instructions:
    - source ~/Devel/Envs/py3_yafas-server/bin/activate

yafas-web-DEPRECATED:
  path: ~/Devel/Projects/yafas-web-DEPRECATED
  instructions:
    - PATH="node_modules/.bin:$PATH"

yafas-web:
  path: ~/Devel/Projects/yafas-web
  instructions:
    - PATH="node_modules/.bin:$PATH"

yafas-web-elm:
  path: ~/Devel/Projects/yafas-web-elm
  instructions:
    - PATH="node_modules/.bin:$PATH"

yafas-website:
  path: ~/Devel/Projects/yafas-website
