backoffice:
  path: ~/Devel/Projects/backoffice/src/
  instructions:
    - source ~/Devel/Envs/py3_backoffice/bin/activate

backoffice-client:
  path: ~/Devel/Projects/backoffice-client/
  instructions:
    - source ~/Devel/Envs/py3_backoffice-client/bin/activate

backoffice-frontend:
  path: ~/Devel/Projects/backoffice-frontend
  instructions:
    - PATH="node_modules/.bin:$PATH"

bn2-backend:
  path: ~/Devel/Projects/bn2-backend/src/
  instructions:
    - source ~/Devel/Envs/py3_bn2-backend/bin/activate

bn2-frontend:
  path: ~/Devel/Projects/bn2-frontend/

build-trigger:
  path: ~/Devel/Projects/build-trigger
  instructions:
    - source ~/Devel/Envs/py3_build-trigger/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

dadata-client:
  path: ~/Devel/Projects/dadata-client
  instructions:
    - source ~/Devel/Envs/py3_dadata-client/bin/activate

diesel:
  path: ~/Devel/Projects/diesel

dotenv-config:
  path: ~/Devel/Projects/dotenv-config
  instructions:
    - source ~/Devel/Envs/py3_dotenv-config/bin/activate

goto_project:
  path: ~/Devel/Projects/goto_project/

insta:
  path: ~/Devel/Projects/insta/
  instructions:
    - source ~/Devel/Envs/py3_insta/bin/activate
    - export FLASK_APP=insta/app.py

learn-rust-by-tutorial:
  path: ~/Devel/Projects/learn-rust-by-tutorial

panoramadv-infrastructure:
  path: ~/Devel/Projects/panoramadv-infrastructure

panoramadv-website:
  path: ~/Devel/Projects/panorama_dv
  instructions:
    - source ~/Devel/Envs/py3_panorama_dv/bin/activate

py_goto_project:
  path: ~/Devel/Projects/py_goto_project/
  instructions:
    - source ~/Devel/Envs/py3_goto-project/bin/activate

pytest-falcon-client:
  path: ~/Devel/Projects/pytest-falcon-client/
  instructions:
    - source ~/Devel/Envs/py3_pytest-falcon-client/bin/activate

kindergarden:
  path: ~/Devel/Projects/kindergarden
  instructions:
    - source ~/Devel/Envs/py3_kindergarden/bin/activate

roistat-aggregator:
  path: ~/Devel/Projects/roistat-aggregator
  instructions:
    - source ~/Devel/Envs/py3_roistat-aggregator/bin/activate
    - export FLASK_APP=app.py
    - export FLASK_DEBUG=1

root-files:
  path: ~/Devel/Projects/root-files/

vimrc:
  path: ~/Devel/Projects/vimrc

yafas-infrastructure:
  path: ~/Devel/Projects/yafas-infrastructure

yafas-server:
  path: ~/Devel/Projects/yafas-server
  instructions:
    - source ~/Devel/Envs/py3_yafas-server/bin/activate

yafas-web-DEPRECATED:
  path: ~/Devel/Projects/yafas-web-DEPRECATED
  instructions:
    - PATH="node_modules/.bin:$PATH"

yafas-web:
  path: ~/Devel/Projects/yafas-web
  instructions:
    - PATH="node_modules/.bin:$PATH"

yafas-website:
  path: ~/Devel/Projects/yafas-website
